### ISSUE TITLE
Why jQueryui as a dep?

### ISSUE THREAD

**Issue by ryanbuiltthat** [lawshe/full-page#3]
I'm curious, I've used fullPage.js before in other projects without ever having to load jQuery UI. Why the need now? 

The reason I'm asking aside from just wondering is this limits any other front-end libraries we could use. My carousel (slider) just turned into a form control because jQui thought it should be that way.

**Comment by debaze** [comment]
Apparently there is a pure JavaScript version of fullpage as well as a JQuery version. 
You could try download the pure JS version from <a href="https://github.com/alvarotrigo/fullPage.js/">The projects Github page</a> and integrate it manually in your meteor project.

Beware though the pure JS version seems to be Alpha.

Rgds
Joris

**Comment by ryanbuiltthat** [comment]
I've used the jQuery version fine before outside of meteor. The jQuery core works fine, I just didn't understand why the ui package was required since it's not needed in the (fullPage) library. I forked the smart package but haven't figured out how to use a package without publishing in meteor yet :) new things are fun!

**Comment by debaze** [comment]
On the essence of the topic: I have no clue why jQuery seems to be included.

On packages:
You can create your own package (or your amended forked one) and use it in your projects by placing it on your machine (f.ex in meteor/packages/packagename) and then in  the yourProject/packages  directory create a symlink to the package you'll want to use. After that you can meteor add packagename . See how on <a href="https://atmospherejs.com/i/publishing">https://atmospherejs.com/i/publishing</a> under Testing package.

Have fun exploring!

**Comment by lawshe** [comment]
jQuery UI was included for optional usage of fullPage.js. From the docs:
"Optionally, you can add the jQuery UI library in case you want to use other easing effects apart from the ones included in the jQuery library (linear, swing) or the one included by default in fullPage.js (easeInQuart)."

I will remove this dependency from the smart package since the UI package can be added independently for those who wish to use other easing effects.

**Comment by ryanbuiltthat** [comment]
It'd be nice if we could add jquery ui easing as a standalone package. I
forgot about the easings because i just grabbed that component and not the
whole library. Thanks for getting back to me and thanks for getting
fullpage in atmosphere! Saved my bacon!
