### ISSUE TITLE
Integrate other packages into fullpage framework

### ISSUE THREAD

**Issue by debaze** [lawshe/full-page#4]
Hello,

I didn't succeed to integrate an interactive shoutbox in the fullpage.js template.

Probably the shoutbox code should wait to execute untill the fullpage template has been rendered. See
<a href="https://github.com/alvarotrigo/fullPage.js#afterrender">Afterrender in fullpage.js docs </a>.

Any ideas/experience on how to archieve this?
My unsuccesful tiral can be seen on <a href="http://full2.meteor.com">full2.meteor.com</a>.
The code for this meteor site is <a href="http://github.com/debaze/full2">On github</a>

The source code for the shoutbox is also on <a href="http://github.com/debaze/shoutbox">github</a>.

Thanks for any tips/advice!
Joris

**Comment by ryanbuiltthat** [comment]
Just thought I'd chime in: I didn't see where you tried to call fullPage in your code. But this is how I init code along with fullPage.js

	Template.home.onRendered(function(){
		// Init fullPage when the template renders
		 $('#fp').fullpage({
		 	// need to wait for fullPage to render
		 	// before any other scripts run that 
		 	// would normall use a $(document).ready()
		 	 afterRender: function(){
		 	 	// in this case I'm firing up a carousel
				$(".carousel").slider({
						height: 350,
						interval: 2000000,
					});
		 	 },
		 });

**Comment by debaze** [comment]
Thanks for the suggestion.

Right now I call the Template.templatename.onRendered in the 
..../templatename.js file.

I'll try calling it from the HTML as I understand you suggest, before letting Handlebars call the shoutbox code,  notwithstanding this looks a bit as a 'hack' to me.

**Comment by ryanbuiltthat** [comment]
Ooops! no that was a typo. the code goes in a javascript file

**Comment by debaze** [comment]
OK, that makes sense :)
I see you initialise the caroussel JQuery in the afterRender: function()
That's exactly what I would like to do with my {{> shoutbox}} handlebars call.
I've been looking into it a while but it doesn't seem straightforward as I dont want to break the reactivity in the shoutbox.. I might post the question StackOverlow at some point.

**Comment by debaze** [comment]
It struck me you couldn't even use template.templName.event({ .... }); style handlers on button clicks etc. So I asked on StackOverflow.

Alvaro answered me<a href="http://stackoverflow.com/questions/29276865/fullpagejs-and-meteor-capture-event-from-template">here</a>. 

In short: You solve the problem by "Use delegation or use verticalCentered:false and scrollOverflow:false."

To Lawshe: You might add to the readme something about this ..
