### ISSUE TITLE
display issue using each

### ISSUE THREAD

**Issue by severin-bruhat** [lawshe/full-page#6]
Hi,

I have a problem when i'm using the #each operator to display a slide template.
Here is my code

`<template name="DisplayProject">`
     `<div class="container">`
          `<div class="row clearfix">`
            `<div class="col-md-12 column">`
           ` <div class="form-group">`
           `  <div id="fullpage">`
              {{#each slides}} 
                {{> slide}}
              {{/each}}
            `</div>`
         ` </div>`
        `</div>`
      `</div>`
  `</div>`
`</template>`

`<template name="slide">`
  `<div class="section" id="section0">`
   ` <div class="opacity">`
      `<h1>text 1</h1>`
   ` </div>`
  `</div> `
  ` <div class="section" id="section1">`
    `<div class="opacity">`
      `<h1>text 2</h1>`
    `</div>`
  `</div> `
`</template>`

When I try to display the page, all the items are listed on the first page, and the scroll doesn't work. 
If I juste remove the #each /each in order to test, it work's. This is weird...

**Comment by lawshe** [comment]
Hello, can you provide a link? You can deploy for free using meteor as a host, https://www.meteor.com/tutorials/blaze/deploying-your-app

**Comment by severin-bruhat** [comment]
I'm afraid I can't for the moment...
Here is the real template : 
`<template name="DisplayProject">`
  `{{{css}}}`
 `<div class="container">`
      `<div class="row clearfix">`
        `<div class="col-md-12 column">`
            `<div class="form-group">`
             `<div id="fullpage">`
             `{{#each slides}} `
                `{{> slide}}`
              `{{/each}}`
           `</div>`
         ` </div>`
        `</div>`
      `</div>`
 `</div>`
`</template>`

`<template name="slide">`
 `<div class="section" id="section{{_id}}">`
  `  <div class="opacity">`
     ` <h1>{{{text}}}</h1>`
    `</div>`
  `</div> `
`</template>`

If I replace the code inside the template "slide"  with a static content, it doesn't display correctly. Then if I remove the #each loop : it works...

**Comment by lawshe** [comment]
Without a site to view or knowing what data is being passed to the helper 'slides' I cannot help you debug this issue. 

This might be a problem with the way fullPage handles the DOM.

**Comment by severin-bruhat** [comment]
I could share you my project on nitrous.io if you hae an account

**Comment by severin-bruhat** [comment]
do you have an account  on nitrous ?

**Comment by severin-bruhat** [comment]
I think I know what the problem is : the code generated in the each loop is generated after the method $('#fullpage').fullpage(); is called. So the different sections are not in the DOM at this moment. That is why it doen't work. But I don't know how t fix it. Any idea ?

**Comment by severin-bruhat** [comment]
I have finaly used a realy bad trick :
 Meteor.setTimeout(function(){
    $('#fullpage').fullpage();
  }, 200);
